#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: HAOwwKnotsb5PUIJs/FGsYMt08FC2FPOF7PI82cgACDCXA7+MaEHoFjCBvB+Ydhm

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2019

# clone directory
clone_folder: G:\Projects\VL\VL.SharedMemory

branches:
  only:
    - master

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  #file: AssemblyInfo.*
  assembly_version: "1.0.{build}-alpha"
  assembly_file_version: "{version}"


install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  #project: src\VL.OpenCV.sln      # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

#before_build:
#  - cd src
#  - nuget restore -DisableParallelProcessing
  

after_build:
  - cd..
  - nuget pack appveyor\VL.SharedMemory.nuspec -Version %APPVEYOR_BUILD_VERSION%-alpha
  - nuget setApiKey %nuget_api_key%
  - nuget push G:\Projects\VL\VL.SharedMemory.%APPVEYOR_BUILD_VERSION%-alpha.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

test: off

notifications:

  # Email
  - provider: Email
    to:
      - makeithappen@nisidis.com
    subject: 'VL.SharedMemory Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true